### ISSUE TITLE
Tietopyynnön aineistojen tarkasteleminen asiakaspäätteellä

### ISSUE THREAD

**Issue by kostiaulis** [Tampere/Tapsa#36]
Asiakaspäätteellä luodun tietopyynnön aineisto tulee olla nähtävillä vain tietopyynnön tehneelle asiakkaalle ja vain määrätyn ajan. 

Alustavasti on suunniteltu, että asiakkaalle voitaisiin tällaisessa tilanteessa toimittaa jokin yksilöllinen koodiavain, jonka syöttämällä järjestelmään asiakas näkisi henkilökohtaisen tietopyyntökansionsa ja saisi nähtäville myös tietopyyntöönsä liitetyn aineiston. Järjestelmän on varmistuttava siitä, että käyttäjä ei pääse näkemään muiden tilaamia aineistoja.

**Comment by ossitammi** [comment]
Mitä kanavaa pitkin tietopyyntö tulee tehdä? Tehdäänkö tämä esimerkiksi julkisessa palvelussa, rakennusvalvontaan muuten yhteydessä olemalla tms?
